export const FETCH_ISSUES = "MainPage/FETCH_ISSUES";
export const FETCH_ISSUES_SUCCESS = "MainPage/FETCH_ISSUES_SUCCESS";
export const FETCH_ISSUES_ERROR = "MainPage/FETCH_ISSUES_ERROR";
export const HIGHLIGHT_ISSUE = "MainPage/HIGHLIGHT_ISSUE";
export const HIGHLIGHT_ISSUE_SUCCESS = "MainPage/HIGHLIGHT_ISSUE_SUCCESS";
export const HIGHLIGHT_ISSUE_ERROR = "MainPage/HIGHLIGHT_ISSUE_ERROR";
